name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  version-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"

      - name: Perform Maven release
        run: mvn -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
